# install_caddy.ps1 — Download Caddy, register it as a Windows Service via NSSM,
# and open the required firewall rules for HTTPS webhook support (ADR-0009).
#
# Run as Administrator after install_windrose.ps1 and install_service.ps1.
# Idempotent: safe to re-run.
#Requires -RunAsAdministrator
param(
    # Public domain name for the TLS certificate (e.g. bot.example.com).
    [Parameter(Mandatory = $true)]
    [string]$Domain,

    # Contact email for Let's Encrypt account.
    [Parameter(Mandatory = $true)]
    [string]$Email,

    # Local port the bot process listens on (FastAPI/uvicorn). Default: 8080.
    [int]$BotPort = 8080,

    # Directory to install Caddy binary and config.
    [string]$CaddyDir = "C:\caddy"
)
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$NSSM_EXE   = "$env:ProgramFiles\nssm\nssm.exe"
$CADDY_EXE  = "$CaddyDir\caddy.exe"
$CADDYFILE  = "$CaddyDir\Caddyfile"
$CADDY_LOG  = "$CaddyDir\logs\caddy.log"
$CADDY_CERT = "$CaddyDir\certs"
$SVC_NAME   = "Caddy"

function Write-Log {
    param([string]$Msg)
    Write-Host "$(Get-Date -Format 'yyyy-MM-ddTHH:mm:ss') [install_caddy] $Msg"
}

Write-Log "=== install_caddy.ps1 started ==="
Write-Log "Domain   : $Domain"
Write-Log "Email    : $Email"
Write-Log "Bot port : $BotPort"
Write-Log "Caddy dir: $CaddyDir"

# ---------------------------------------------------------------------------
# 1. Verify NSSM
# ---------------------------------------------------------------------------
if (-not (Test-Path $NSSM_EXE)) {
    Write-Log "FATAL: NSSM not found at $NSSM_EXE. Run bootstrap.ps1 first."
    exit 1
}

# ---------------------------------------------------------------------------
# 2. Create directories
# ---------------------------------------------------------------------------
New-Item -ItemType Directory -Force -Path $CaddyDir       | Out-Null
New-Item -ItemType Directory -Force -Path "$CaddyDir\logs" | Out-Null
New-Item -ItemType Directory -Force -Path $CADDY_CERT      | Out-Null
Write-Log "Directories created OK"

# ---------------------------------------------------------------------------
# 3. Download Caddy binary (if not already present)
# ---------------------------------------------------------------------------
if (-not (Test-Path $CADDY_EXE)) {
    Write-Log "Downloading Caddy for Windows amd64..."
    $url = "https://caddyserver.com/api/download?os=windows&arch=amd64&p=github.com%2Fcaddy-dns%2Fcloudflare"
    # Plain Caddy without DNS plugin (simpler, uses HTTP-01 ACME challenge):
    $url = "https://caddyserver.com/api/download?os=windows&arch=amd64"
    Invoke-WebRequest -Uri $url -OutFile $CADDY_EXE -UseBasicParsing
    Write-Log "Caddy downloaded to $CADDY_EXE"
} else {
    Write-Log "Caddy already present: $CADDY_EXE"
}

# ---------------------------------------------------------------------------
# 4. Write Caddyfile
# ---------------------------------------------------------------------------
Write-Log "Writing Caddyfile..."
$caddyfileContent = @"
# Caddyfile — auto-generated by install_caddy.ps1
# Edit manually for advanced configuration.

{
    # Persistent certificate storage — required when running as SYSTEM.
    storage file_system {
        root $($CADDY_CERT -replace '\\','/')
    }
    email $Email
}

$Domain {
    tls $Email

    # Suppress bot token from access logs (ADR-0007, ADR-0009).
    log {
        output file $($CaddyDir -replace '\\','/')/logs/access.log
        format filter {
            wrap json
            fields {
                request>uri replace /webhook/ /webhook/[REDACTED]/
            }
        }
    }

    # Telegram webhook — proxied to bot process on localhost.
    handle /webhook/* {
        reverse_proxy localhost:$BotPort
    }

    # Health endpoint — no token in path, used by Docker healthcheck.
    handle /health {
        reverse_proxy localhost:$BotPort
    }

    # Block everything else.
    respond 404
}
"@

[System.IO.File]::WriteAllText(
    $CADDYFILE,
    $caddyfileContent,
    (New-Object System.Text.UTF8Encoding($false))
)
Write-Log "Caddyfile written: $CADDYFILE"

# ---------------------------------------------------------------------------
# 5. Register Caddy as Windows Service via NSSM
# ---------------------------------------------------------------------------
Write-Log "Registering Caddy Windows Service..."
$existing = Get-Service -Name $SVC_NAME -ErrorAction SilentlyContinue
if ($existing) {
    if ($existing.Status -eq 'Running') {
        & $NSSM_EXE stop $SVC_NAME
        Start-Sleep -Seconds 3
    }
    & $NSSM_EXE remove $SVC_NAME confirm
}

& $NSSM_EXE install $SVC_NAME $CADDY_EXE "run --config `"$CADDYFILE`""
& $NSSM_EXE set $SVC_NAME DisplayName  "Caddy Reverse Proxy"
& $NSSM_EXE set $SVC_NAME Description  "Caddy TLS reverse proxy for Windrose Telegram bot (ADR-0009)"
& $NSSM_EXE set $SVC_NAME Start        SERVICE_AUTO_START
& $NSSM_EXE set $SVC_NAME AppDirectory $CaddyDir
& $NSSM_EXE set $SVC_NAME AppStdout    $CADDY_LOG
& $NSSM_EXE set $SVC_NAME AppStderr    $CADDY_LOG
& $NSSM_EXE set $SVC_NAME AppRotateFiles  1
& $NSSM_EXE set $SVC_NAME AppRotateBytes  10485760  # 10 MB
& $NSSM_EXE set $SVC_NAME AppRestartDelay 5000

Write-Log "Caddy service registered OK"

# ---------------------------------------------------------------------------
# 6. Windows Firewall rules
# ---------------------------------------------------------------------------
Write-Log "Configuring Windows Firewall..."

$rules = @(
    @{ Name = "Caddy HTTPS (443)"; Port = 443 },
    @{ Name = "Caddy HTTP (80)";   Port = 80  }
)
foreach ($rule in $rules) {
    $existing_fw = Get-NetFirewallRule -DisplayName $rule.Name -ErrorAction SilentlyContinue
    if (-not $existing_fw) {
        New-NetFirewallRule `
            -DisplayName $rule.Name `
            -Direction   Inbound `
            -Protocol    TCP `
            -LocalPort   $rule.Port `
            -Action      Allow | Out-Null
        Write-Log "Firewall rule added: $($rule.Name)"
    } else {
        Write-Log "Firewall rule already exists: $($rule.Name)"
    }
}

# Block direct access to the bot port from outside (bot is internal-only).
$botRuleName = "Block bot port $BotPort from external"
$existingBot = Get-NetFirewallRule -DisplayName $botRuleName -ErrorAction SilentlyContinue
if (-not $existingBot) {
    New-NetFirewallRule `
        -DisplayName      $botRuleName `
        -Direction        Inbound `
        -Protocol         TCP `
        -LocalPort        $BotPort `
        -Action           Block `
        -RemoteAddress    Internet | Out-Null
    Write-Log "Firewall rule added: $botRuleName"
}

# ---------------------------------------------------------------------------
# 7. Start Caddy
# ---------------------------------------------------------------------------
Write-Log "Starting Caddy service..."
try {
    Start-Service -Name $SVC_NAME -ErrorAction Stop
    Start-Sleep -Seconds 3
    $status = (Get-Service -Name $SVC_NAME).Status
    Write-Log "Caddy service status: $status"
} catch {
    Write-Log "WARNING: Could not start Caddy now: $_"
    Write-Log "         Start manually: nssm start Caddy"
}

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------
Write-Log ""
Write-Log "=== install_caddy.ps1 complete ==="
Write-Log "Next steps:"
Write-Log "  1. Ensure DNS A record for $Domain points to this machine's public IP."
Write-Log "  2. Ports 80 and 443 must be forwarded at the router/NAT to this machine."
Write-Log "  3. Set USE_WEBHOOK=true and WEBHOOK_BASE_URL=https://$Domain in .env"
Write-Log "  4. Restart the bot: .\stop.ps1; .\start.ps1"
Write-Log "  5. Verify: curl https://$Domain/health"
Write-Log "  6. Test TLS: https://www.ssllabs.com/ssltest/analyze.html?d=$Domain"
Write-Log ""
Write-Log "Service commands:"
Write-Log "  Start-Service Caddy"
Write-Log "  Stop-Service  Caddy"
Write-Log "  Get-Content $CADDY_LOG -Wait"
